# notify:
#   - github_commit_status:
#       context: "ci/tests"

agents:
  image: "docker.elastic.co/eck-dev/bk-agent:latest"
  cpu: "4"
  memory: "2G"

steps:
  # - group: build
  #   steps:
  #     - command: "make e2e-docker-multiarch-build"
  #     - command: "make build-operator-image"
  #     - command: "make run-deployer apply-psp"

  - group: "build"
    steps:

      - label: ":docker: operator container image"
        commands:
          - make -sC .ci get-test-artifacts-bk
          - .ci/setenvconfig pr
          - make operator-buildah

      - label: ":docker: e2e-tests container image"
        commands:
          - make -sC .ci get-test-artifacts-bk
          - .ci/setenvconfig pr
          - make e2e-buildah

  - group: checks
    steps:

      - label: ":go: lint"
        command: "make lint check-local-changes"
        agents:
          memory: "5G"

      - label: ":go: generate"
        command: "make generate check-local-changes"

      - label: ":go: checks"
        command: "make check-license-header check-predicates shellcheck reattach-pv"

  - group: tests
    steps:

      - label: ":go: unit-tests"
        command: "make unit-xml"
        agents:
          memory: "4G"

      - label: ":go: integration-tests"
        command: "make integration-xml"
        agents:
          memory: "4G"

  # - group: e2e-tests
  #   steps:
  #   - command: ".ci/setenvconfig pr && make run-deployer apply-psp"
  #   - wait
  #   - command: ".ci/setenvconfig pr && make e2e-run"
  #   - wait: ~
  #     continue_on_failure: true
  #   - command: ".ci/setenvconfig cleanup/gke && make run-deployer"

#  - wait
#  - command: make "set-kubeconfig e2e-run e2e-generate-xml"
