# notify:
#   - github_commit_status:
#       context: "ci/tests"

agents:
  image: "docker.elastic.co/eck-dev/bk-agent:latest"
  cpu: "4"
  memory: "2G"

steps:
  # - group: build
  #   steps:
  #     - command: "make e2e-docker-multiarch-build"
  #     - command: "make build-operator-image"
  #     - command: "make run-deployer apply-psp"

  - group: "build"
    steps:

      - label: ":docker: operator container image"
        commands:
          - make -sC .ci get-test-artifacts-bk
          - .ci/setenvconfig pr
          - make operator-buildah

      - label: ":docker: e2e-tests container image"
        commands:
          - make -sC .ci get-test-artifacts-bk
          - .ci/setenvconfig pr
          - make e2e-buildah

  - group: checks
    steps:

      - label: ":go: lint"
        command: "make lint check-local-changes"
        agents:
          cpu: "6"
          memory: "6G"

      - label: ":go: generate"
        command: "make generate check-local-changes"

      - label: ":go: checks"
        command: "make check-license-header check-predicates shellcheck reattach-pv"

  - group: tests
    steps:

      - label: ":go: unit-tests"
        command: "make unit-xml"
        agents:
          memory: "4G"

      - label: ":go: integration-tests"
        command: "make integration-xml"
        agents:
          memory: "4G"

  - group: e2e-tests
    steps:
    
    - label: ":k8s: create k8s"
      commands:
        - .ci/setenvconfig pr
        - make run-deployer apply-psp

    - wait
    - label: ":k8s: e2e-tests"
      commands:
        - make -sC .ci get-test-artifacts-bk
        - .ci/setenvconfig pr
        - make set-kubeconfig e2e-run e2e-generate-xml
      agents:
        memory: "6G"

    - wait: ~
      continue_on_failure: true
    - label: ":k8s: delete k8s"
      command: ".ci/setenvconfig cleanup/gke && make run-deployer"
